name = "todo-app"
main = "src/index.ts"
compatibility_date = "2025-01-25"

# compatibility_flags = [ "nodejs_compat" ]

[vars]
JWT_SECRET = "secret"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB"
database_name = "todo-app-database"
database_id = "local" # 空欄だと local で接続できない

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1